version: '3.8'

services:
  db:
    image: mysql:8
    container_name: cloudstore-db
    restart: always
    environment:
      MYSQL_DATABASE: ecommercedb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: cloudstore-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://db:3306/ecommercedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
      FAKESTORE_API_URL: https://fakestoreapi.com/products
    ports:
      - "8080:8080"

volumes:
  mysql-data: