spring.application.name=CloudStore
server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/cloudstore?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@1345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# FakeStore API URL
fakestore.api.url=https://fakestoreapi.com/products

# Logging
logging.level.org.springframework.security=INFO
